[package]
name = "responder"
version = "0.1.0"
authors = ["Livio Ribeiro <livioribeiro@outlook.com>"]
license = "MIT OR Apache-2.0"

[dependencies]
hyper = "0.9"
quire = "0.1"
rustc-serialize = "0.3"
regex = "0.1"
clap = "2.2"
